# Generated by Django 5.0.2 on 2024-03-23 13:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('type', models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')], default=0, max_length=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Réaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('like', models.BooleanField(default=False)),
                ('poste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.poste')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.user')),
            ],
        ),
    ]
