# Generated by Django 5.0.2 on 2024-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0002_poste_réaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='type',
            field=models.IntegerField(choices=[(0, 'Offre'), (1, 'Demande')], default=0),
        ),
    ]
