# Generated by Django 5.0.2 on 2024-03-23 14:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0003_alter_poste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evènement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('intitulé', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('lieu', models.CharField(max_length=100)),
                ('contactInfo', models.CharField(max_length=8)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('localisation', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('contactInfo', models.CharField(max_length=8)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('texte', models.CharField(max_length=100)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('typeStg', models.IntegerField(choices=[(1, 'Ouvrier'), (2, 'Technicien'), (3, 'PFE')], default=1)),
                ('société', models.CharField(max_length=50)),
                ('durée', models.IntegerField()),
                ('sujet', models.CharField(max_length=100)),
                ('contactInfo', models.CharField(max_length=8)),
                ('spécialité', models.CharField(max_length=50)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.poste')),
                ('départ', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('heure_dep', models.TimeField(default=datetime.datetime.now)),
                ('nbre_sièges', models.IntegerField()),
                ('contactInfo', models.CharField(max_length=8)),
            ],
            bases=('StudentHelp.poste',),
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('evènement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.evènement')),
                ('club', models.CharField(max_length=50)),
            ],
            bases=('StudentHelp.evènement',),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('evènement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudentHelp.evènement')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            bases=('StudentHelp.evènement',),
        ),
    ]
