# Generated by Django 5.0.2 on 2024-04-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0004_evènement_logement_recommandation_stage_transport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.poste')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentHelp.user')),
            ],
        ),
    ]
