# Generated by Django 5.0.2 on 2024-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0005_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
