# Generated by Django 5.0.2 on 2024-05-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='caption',
            field=models.CharField(max_length=10000, null=True, verbose_name='Caption'),
        ),
    ]
