# Generated by Django 4.1.13 on 2024-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentHelp', '0010_poste_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='type_poste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
